apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: densify-resource-optimization-webhook
  # Uncomment the below annotation 'cert-manager.io/inject-ca-from' if using cert-manager
  #annotations:
  #      cert-manager.io/inject-ca-from: densify-automation/densify-automation-cert
webhooks:
  - name: resource-optimizer.densify.com
    clientConfig:
      service:
        name: densify-webhook-service
        namespace: densify-automation
        path: "/mutate"
      # Replace <YOUR_CA_BUNDLE_BASE64> with your base64-encoded CA certificate
      caBundle: ""
    failurePolicy: Ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]  
        resources: ["pods"]
        scope: "Namespaced"
    objectSelector:
      matchLabels:
        densify-automation: "true"
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    timeoutSeconds: 10