apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: densify-resource-optimization-webhook
  annotations:
        cert-manager.io/inject-ca-from: densify-automation/densify-automation-cert
webhooks:
  - name: resource-optimizer.densify.com
    clientConfig:
      service:
        name: densify-webhook-service
        namespace: densify-automation
        path: "/mutate"
      caBundle: ""
    failurePolicy: Ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]  
        resources: ["pods"]
        scope: "Namespaced"
    objectSelector:
      matchLabels:
        densify-automation: "true"
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    timeoutSeconds: 10