apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: densify-automation
  name: cleanup-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-role-binding
  namespace: densify-automation
subjects:
- kind: ServiceAccount
  name: cleanup-service-account
  namespace: densify-automation
roleRef:
  kind: Role
  name: cleanup-role
  apiGroup: rbac.authorization.k8s.io
