apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: densify-recommendations-pvc
  namespace: densify-automation
spec:
  volumeBindingMode: Immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
